### ISSUE TITLE
求助TTS部署报错

### ISSUE THREAD

**Issue by Franklin-L** [radxa-edge/TPU-Edge-AI#3]
![image](https://github.com/radxa-edge/TPU-Edge-AI/assets/146100070/affc035b-178b-4a5a-ac2b-a64c7e07fca8)
请问这个是为什么呀执行到最后一步了启动报错了

**Comment by zifeng-radxa** [comment]
请使用 https://github.com/zifeng-radxa/EmotiVoice-TPU/tree/radxa_v0.1.2 这个仓库并 按照 https://github.com/radxa-edge/TPU-Edge-AI/blob/main/radxa_docs/CH/EmotiVoice.md 这个文档来部署

**Comment by zifeng-radxa** [comment]
注意是 radxa_v0.1.2 分支

**Comment by baifengbai** [comment]
gradio版本的问题，info参数有些版本没有，去掉即可
